version: "3.4"

networks:
  jaguar:
    external:
      name: jaguar.localhost

services:
  jaguarapi:
    image: jaguar/api:local-dev
    container_name: jaguar_api
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - ./jaguar/.env
    networks:
      default:
      jaguar:
    command: bash -c "python waitForPostgres.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8088"
    volumes:
      - ./jaguar:/jaguar
    ports:
      - "8088:8088"


  jaguardb:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      default:
      jaguar:
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    container_name: jaguar_db

volumes:
  postgres-data:
