apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # -------------------
  # namespaces
  # -------------------
  - k8s/namespace.yaml
  # -------------------
  # postgres
  # -------------------
  - k8s/postgres-storage.yaml
  - k8s/postgres.yaml
  - k8s/postgres-service.yaml
  # -------------------
  # jaguar app
  # -------------------
  - k8s/jaguar-api.yaml
  - k8s/jaguar-service.yaml

namespace: production
commonLabels:
  author: jhonsfran

configMapGenerator:
  - name: app-config
    envs: [k8s/app.env]
