#!/usr/bin/env bash

python3 waitForPostgres.py && \
python3 manage.py makemigrations && \
python3 manage.py migrate && \
python3 manage.py createinitialrevisions && \
python3 manage.py collectstatic --noinput && \
uwsgi --ini /jaguar/jaguar/uwsgi.ini