apiVersion: v1
kind: Service
metadata:
  name: jaguar-svc
spec:
  type: NodePort
  selector:
   app: jaguar-app
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      protocol: TCP
      nodePort: 30080